/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110165-g9a245bdf5d-20230403"
#endif /* AVUTIL_FFVERSION_H */
